# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishListApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishList', related_query_name='wishList_query', to='wishListApp.Items'),
        ),
    ]
